version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run: conda config --add channels conda-forge
      - run: conda config --set always_yes true
      - run: conda config --set quiet true
      - run: conda install iris
      - run:
          name: Install GCEm
          command:
            pip install -U pip
            pip install -r tests_requirements.txt
            pip install -e .
      - run:
          command: python -m unittest tests
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
