version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  test:
    docker:
      - image: continuumio/miniconda3
    executor: python/default
    steps:
      - checkout
      - run: conda config --add channels conda-forge
      - run: conda config --set always_yes true
      - run: conda config --set quiet true
      - run: conda install iris
      - run: pip install -r tests_requirements.txt
      - run:
          name: Run tests
          command: |
            pytest -v --cov=./GCEm ./tests
      - run:
          name: Upload coverage report
          command: |
            bash <(curl -s https://codecov.io/bash) -t "${CODECOV_TOKEN}"

workflows:
  main:
    jobs:
      - test
